services:
  nginx:
    image: nginx:latest
    ports:
      - "9090:80"
    volumes:
      - ./clothes3:/usr/share/nginx/html/img:ro
      # - ./clothes3:/usr/share/nginx/html/img3:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro